name: Build Mac App

on:
  push:
 workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: brew install cmake

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make